name: CI/CD Pipeline for AI Agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    name: Run Tests and Linter
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are critical linting errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Show all warnings but do not fail the build
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      # For test execution, a test database is usually required.
      # In a real CI setup, you should spin up a test DB (e.g., using services or testcontainers).
      # For simplicity, tests are skipped here.
      # run: |
      #   pip install pytest
      #   pytest
      run: echo "Skipping tests in CI for simplicity. Set up a test DB for real scenarios."


  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test-and-lint # This job runs only if the test-and-lint job succeeds
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/lo
